// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuskzngfmttcqbnepkbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1c2t6bmdmbXR0Y3FibmVwa2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNjY5OTAsImV4cCI6MjA1MTg0Mjk5MH0.WRmFj3X2YnWsTeE9RXh0iGLTcprbbGJCijD8BlGDTJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);